package main

import (
	"html/template"
	"io"
)

const indexTempl = `
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <title>{{ .Path }}</title>
</head>

<body>
  <h1>Content of {{ .Path }}: </h1>
  <hr />
  {{ with . }}
  <ul>
	{{ range .Entries }}
	<li><a href="{{ . }}/">{{ . }}</a></li>
	{{ end }}
  </ul>
  {{ end }}
  <hr />
  <p>Generated by <a href="https://github.com/Mr-Dai/http-server">mr-dai/http-server</a>, v{{ .Version }}</p>
</body> 
</html>
`

var index = template.Must(template.New("index").Parse(indexTempl))

type indexInfo struct {
	Path    string
	Entries []string
	Version string
}

func listDir(path string, names []string, out io.Writer) {
	if path != "/" {
		names = append([]string{".."}, names...)
	}
	index.Execute(out, indexInfo{path, names, version})
}
